@echo off
setlocal EnableExtensions
chcp 65001 >nul

rem ============================================================
rem 90_cleanup_legacy_tools.bat
rem Moves old unnumbered tools to tools\legacy_* so the tools folder stays clean.
rem Safe utility: it does not touch numbered tools, checks, output logs, or EXE files.
rem ============================================================

cd /d "%~dp0.."
set "ROOT=%CD%"
set "TOOLS=%ROOT%\tools"
set "STAMP=%date:~-4%-%date:~3,2%-%date:~0,2%_%time:~0,2%-%time:~3,2%-%time:~6,2%"
set "STAMP=%STAMP: =0%"
set "LEGACY=%TOOLS%\legacy_%STAMP%"

if not exist "%LEGACY%" mkdir "%LEGACY%" >nul 2>nul

echo ============================================================
echo CLEANUP LEGACY TOOLS
echo ============================================================
echo Moving old files to:
echo %LEGACY%
echo.

call :move_if_exists "%TOOLS%\run_dev.bat"
call :move_if_exists "%TOOLS%\run_frontend_contract_check.bat"
call :move_if_exists "%TOOLS%\dump_project_code.bat"
call :move_if_exists "%TOOLS%\dump_project_tree.bat"
call :move_if_exists "%TOOLS%\docker_build_run.bat"
call :move_if_exists "%TOOLS%\build_exe.bat"
call :move_if_exists "%TOOLS%\frontend_contract_check.py"
call :move_if_exists "%TOOLS%\project_tree.txt"
call :move_if_exists "%ROOT%\PATCH_KEYS.txt"

rem Old helper launchers in tools\out are generated by 01_run_dev.bat and can stay in out.

echo.
echo [OK] Cleanup finished.
echo Numbered main scripts are:
echo   tools\01_run_dev.bat
echo   tools\02_check_frontend_contract.bat
echo   tools\03_dump_project_code.bat
echo   tools\04_dump_project_tree.bat
echo   tools\05_docker_build_run.bat
echo   tools\06_build_exe.bat
echo   tools\07_check_locked_state.bat
echo   tools\08_create_desktop_shortcut.bat
echo   tools\90_cleanup_legacy_tools.bat
echo.
pause
exit /b 0

:move_if_exists
if exist "%~1" (
  echo move %~nx1
  move /Y "%~1" "%LEGACY%\" >nul
)
exit /b 0
